version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - CLOUDINARY_CLOUD_NAME=your_cloud_name
      - CLOUDINARY_API_KEY=your_api_key
      - CLOUDINARY_API_SECRET=your_api_secret
    volumes:
      - .:/app 